server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/picture?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/picture?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 开启大文件上传功能
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    # MyBatis 配置
    # 关闭下划线映射驼峰命名 ， 因为数据库字段是驼峰命名
    map-underscore-to-camel-case: false
    # 仅在开发环境下开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 逻辑删除字段名
      logic-delete-value: 1
      logic-not-delete-value: 0
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.itjj.picturebackend.controller
